name: masterevent
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  http: 1.3.0

  
 
  flutter_local_notifications: ^19.0.0  
  timezone: ^0.10.0                  
  table_calendar: ^3.1.3             
  
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0  

 
  image_picker: ^1.1.2 
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
 