name: event
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  intl: 0.20.2
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0
  flutter_localizations:
    sdk: flutter

  http: ^1.3.0
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.0
  table_calendar: ^3.1.3
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.7.0
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/p1.jpg
    - assets/p2.jpg
    - assets/s1.jpg
    - assets/s2.jpg
    - assets/fareed.jpg
    - assets/1948.jpg
    - assets/kob.jpg
    - assets/ma.jpg
    - assets/jeb.jpg
    - assets/f1.jpg
    - assets/f2.jpg
    - assets/dd1.jpg
    - assets/tal1.jpg
    - assets/tal2.jpg
    - assets/tal3.jpg
    - assets/sh1.jpg
    - assets/sh2.jpg

  fonts:
    - family: Boldnose
      fonts:
        - asset: fonts/Boldonse-Regular.ttf
